# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excuse', '0002_auto_20170824_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'BlackList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'WhiteList',
                'managed': False,
            },
        ),
    ]
