# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excuse', '0003_blacklist_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dangersrc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('time', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'DangerSrc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Packetin',
            fields=[
                ('time', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('packetin', models.IntegerField(db_column='PacketIn')),
            ],
            options={
                'db_table': 'PacketIn',
                'managed': False,
            },
        ),
    ]
