# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excuse', '0004_dangersrc_packetin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sysstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'sysStatus',
                'managed': False,
            },
        ),
    ]
